/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.vnpt.data.cms.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandler;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerRegistryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Criterion;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Disjunction;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.dao.orm.Property;
import com.liferay.portal.kernel.dao.orm.PropertyFactoryUtil;
import com.liferay.portal.kernel.dao.orm.RestrictionsFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.vnpt.data.cms.model.DicDataType;
import vn.vnpt.data.cms.service.DicDataTypeLocalService;
import vn.vnpt.data.cms.service.DicDataTypeLocalServiceUtil;
import vn.vnpt.data.cms.service.persistence.CatalogFieldNamePersistence;
import vn.vnpt.data.cms.service.persistence.CatalogPersistence;
import vn.vnpt.data.cms.service.persistence.DicDataTypePersistence;

/**
 * Provides the base implementation for the dic data type local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.vnpt.data.cms.service.impl.DicDataTypeLocalServiceImpl}.
 * </p>
 *
 * @author vnpt
 * @see vn.vnpt.data.cms.service.impl.DicDataTypeLocalServiceImpl
 * @generated
 */
public abstract class DicDataTypeLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DicDataTypeLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DicDataTypeLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DicDataTypeLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dic data type to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DicDataTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dicDataType the dic data type
	 * @return the dic data type that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DicDataType addDicDataType(DicDataType dicDataType) {
		dicDataType.setNew(true);

		return dicDataTypePersistence.update(dicDataType);
	}

	/**
	 * Creates a new dic data type with the primary key. Does not add the dic data type to the database.
	 *
	 * @param dicDataTypeId the primary key for the new dic data type
	 * @return the new dic data type
	 */
	@Override
	@Transactional(enabled = false)
	public DicDataType createDicDataType(long dicDataTypeId) {
		return dicDataTypePersistence.create(dicDataTypeId);
	}

	/**
	 * Deletes the dic data type with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DicDataTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dicDataTypeId the primary key of the dic data type
	 * @return the dic data type that was removed
	 * @throws PortalException if a dic data type with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DicDataType deleteDicDataType(long dicDataTypeId)
		throws PortalException {

		return dicDataTypePersistence.remove(dicDataTypeId);
	}

	/**
	 * Deletes the dic data type from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DicDataTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dicDataType the dic data type
	 * @return the dic data type that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DicDataType deleteDicDataType(DicDataType dicDataType) {
		return dicDataTypePersistence.remove(dicDataType);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DicDataType.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dicDataTypePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.vnpt.data.cms.model.impl.DicDataTypeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dicDataTypePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.vnpt.data.cms.model.impl.DicDataTypeModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dicDataTypePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dicDataTypePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dicDataTypePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DicDataType fetchDicDataType(long dicDataTypeId) {
		return dicDataTypePersistence.fetchByPrimaryKey(dicDataTypeId);
	}

	/**
	 * Returns the dic data type matching the UUID and group.
	 *
	 * @param uuid the dic data type's UUID
	 * @param groupId the primary key of the group
	 * @return the matching dic data type, or <code>null</code> if a matching dic data type could not be found
	 */
	@Override
	public DicDataType fetchDicDataTypeByUuidAndGroupId(
		String uuid, long groupId) {

		return dicDataTypePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the dic data type with the primary key.
	 *
	 * @param dicDataTypeId the primary key of the dic data type
	 * @return the dic data type
	 * @throws PortalException if a dic data type with the primary key could not be found
	 */
	@Override
	public DicDataType getDicDataType(long dicDataTypeId)
		throws PortalException {

		return dicDataTypePersistence.findByPrimaryKey(dicDataTypeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(dicDataTypeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DicDataType.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dicDataTypeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dicDataTypeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DicDataType.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dicDataTypeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(dicDataTypeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DicDataType.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dicDataTypeId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					Criterion modifiedDateCriterion =
						portletDataContext.getDateRangeCriteria("modifiedDate");

					Criterion statusDateCriterion =
						portletDataContext.getDateRangeCriteria("statusDate");

					if ((modifiedDateCriterion != null) &&
						(statusDateCriterion != null)) {

						Disjunction disjunction =
							RestrictionsFactoryUtil.disjunction();

						disjunction.add(modifiedDateCriterion);
						disjunction.add(statusDateCriterion);

						dynamicQuery.add(disjunction);
					}

					Property workflowStatusProperty =
						PropertyFactoryUtil.forName("status");

					if (portletDataContext.isInitialPublication()) {
						dynamicQuery.add(
							workflowStatusProperty.ne(
								WorkflowConstants.STATUS_IN_TRASH));
					}
					else {
						StagedModelDataHandler<?> stagedModelDataHandler =
							StagedModelDataHandlerRegistryUtil.
								getStagedModelDataHandler(
									DicDataType.class.getName());

						dynamicQuery.add(
							workflowStatusProperty.in(
								stagedModelDataHandler.
									getExportableStatuses()));
					}
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<DicDataType>() {

				@Override
				public void performAction(DicDataType dicDataType)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, dicDataType);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(DicDataType.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dicDataTypePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return dicDataTypeLocalService.deleteDicDataType(
			(DicDataType)persistedModel);
	}

	public BasePersistence<DicDataType> getBasePersistence() {
		return dicDataTypePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dicDataTypePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the dic data types matching the UUID and company.
	 *
	 * @param uuid the UUID of the dic data types
	 * @param companyId the primary key of the company
	 * @return the matching dic data types, or an empty list if no matches were found
	 */
	@Override
	public List<DicDataType> getDicDataTypesByUuidAndCompanyId(
		String uuid, long companyId) {

		return dicDataTypePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of dic data types matching the UUID and company.
	 *
	 * @param uuid the UUID of the dic data types
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of dic data types
	 * @param end the upper bound of the range of dic data types (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching dic data types, or an empty list if no matches were found
	 */
	@Override
	public List<DicDataType> getDicDataTypesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<DicDataType> orderByComparator) {

		return dicDataTypePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the dic data type matching the UUID and group.
	 *
	 * @param uuid the dic data type's UUID
	 * @param groupId the primary key of the group
	 * @return the matching dic data type
	 * @throws PortalException if a matching dic data type could not be found
	 */
	@Override
	public DicDataType getDicDataTypeByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return dicDataTypePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the dic data types.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.vnpt.data.cms.model.impl.DicDataTypeModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dic data types
	 * @param end the upper bound of the range of dic data types (not inclusive)
	 * @return the range of dic data types
	 */
	@Override
	public List<DicDataType> getDicDataTypes(int start, int end) {
		return dicDataTypePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dic data types.
	 *
	 * @return the number of dic data types
	 */
	@Override
	public int getDicDataTypesCount() {
		return dicDataTypePersistence.countAll();
	}

	/**
	 * Updates the dic data type in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DicDataTypeLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dicDataType the dic data type
	 * @return the dic data type that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DicDataType updateDicDataType(DicDataType dicDataType) {
		return dicDataTypePersistence.update(dicDataType);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DicDataTypeLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		dicDataTypeLocalService = (DicDataTypeLocalService)aopProxy;

		_setLocalServiceUtilService(dicDataTypeLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DicDataTypeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DicDataType.class;
	}

	protected String getModelClassName() {
		return DicDataType.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dicDataTypePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DicDataTypeLocalService dicDataTypeLocalService) {

		try {
			Field field = DicDataTypeLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, dicDataTypeLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CatalogPersistence catalogPersistence;

	@Reference
	protected CatalogFieldNamePersistence catalogFieldNamePersistence;

	protected DicDataTypeLocalService dicDataTypeLocalService;

	@Reference
	protected DicDataTypePersistence dicDataTypePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}