/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.vnpt.data.cms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Catalog service. Represents a row in the &quot;VNPT_Catalog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>vn.vnpt.data.cms.model.impl.CatalogModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>vn.vnpt.data.cms.model.impl.CatalogImpl</code>.
 * </p>
 *
 * @author vnpt
 * @see Catalog
 * @generated
 */
@ProviderType
public interface CatalogModel
	extends BaseModel<Catalog>, GroupedModel, LocalizedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a catalog model instance should use the {@link Catalog} interface instead.
	 */

	/**
	 * Returns the primary key of this catalog.
	 *
	 * @return the primary key of this catalog
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this catalog.
	 *
	 * @param primaryKey the primary key of this catalog
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this catalog.
	 *
	 * @return the uuid of this catalog
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this catalog.
	 *
	 * @param uuid the uuid of this catalog
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the catalog ID of this catalog.
	 *
	 * @return the catalog ID of this catalog
	 */
	public long getCatalogId();

	/**
	 * Sets the catalog ID of this catalog.
	 *
	 * @param catalogId the catalog ID of this catalog
	 */
	public void setCatalogId(long catalogId);

	/**
	 * Returns the group ID of this catalog.
	 *
	 * @return the group ID of this catalog
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this catalog.
	 *
	 * @param groupId the group ID of this catalog
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this catalog.
	 *
	 * @return the company ID of this catalog
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this catalog.
	 *
	 * @param companyId the company ID of this catalog
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this catalog.
	 *
	 * @return the user ID of this catalog
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this catalog.
	 *
	 * @param userId the user ID of this catalog
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this catalog.
	 *
	 * @return the user uuid of this catalog
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this catalog.
	 *
	 * @param userUuid the user uuid of this catalog
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this catalog.
	 *
	 * @return the user name of this catalog
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this catalog.
	 *
	 * @param userName the user name of this catalog
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this catalog.
	 *
	 * @return the create date of this catalog
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this catalog.
	 *
	 * @param createDate the create date of this catalog
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this catalog.
	 *
	 * @return the modified date of this catalog
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this catalog.
	 *
	 * @param modifiedDate the modified date of this catalog
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the table name of this catalog.
	 *
	 * @return the table name of this catalog
	 */
	@AutoEscape
	public String getTableName();

	/**
	 * Sets the table name of this catalog.
	 *
	 * @param tableName the table name of this catalog
	 */
	public void setTableName(String tableName);

	/**
	 * Returns the title of this catalog.
	 *
	 * @return the title of this catalog
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this catalog in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this catalog
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this catalog in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this catalog. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this catalog in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this catalog
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this catalog in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this catalog
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this catalog.
	 *
	 * @return the locales and localized titles of this catalog
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this catalog.
	 *
	 * @param title the title of this catalog
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this catalog in the language.
	 *
	 * @param title the localized title of this catalog
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this catalog in the language, and sets the default locale.
	 *
	 * @param title the localized title of this catalog
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this catalog from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this catalog
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this catalog from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this catalog
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this catalog.
	 *
	 * @return the description of this catalog
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this catalog in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this catalog
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this catalog in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this catalog. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this catalog in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this catalog
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this catalog in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this catalog
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this catalog.
	 *
	 * @return the locales and localized descriptions of this catalog
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this catalog.
	 *
	 * @param description the description of this catalog
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this catalog in the language.
	 *
	 * @param description the localized description of this catalog
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this catalog in the language, and sets the default locale.
	 *
	 * @param description the localized description of this catalog
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this catalog from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this catalog
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this catalog from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this catalog
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	/**
	 * Returns the version of this catalog.
	 *
	 * @return the version of this catalog
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this catalog.
	 *
	 * @param version the version of this catalog
	 */
	public void setVersion(String version);

	/**
	 * Returns the visibility of this catalog.
	 *
	 * @return the visibility of this catalog
	 */
	public boolean getVisibility();

	/**
	 * Returns <code>true</code> if this catalog is visibility.
	 *
	 * @return <code>true</code> if this catalog is visibility; <code>false</code> otherwise
	 */
	public boolean isVisibility();

	/**
	 * Sets whether this catalog is visibility.
	 *
	 * @param visibility the visibility of this catalog
	 */
	public void setVisibility(boolean visibility);

	/**
	 * Returns the cat type of this catalog.
	 *
	 * @return the cat type of this catalog
	 */
	public int getCatType();

	/**
	 * Sets the cat type of this catalog.
	 *
	 * @param catType the cat type of this catalog
	 */
	public void setCatType(int catType);

	/**
	 * Returns the status of this catalog.
	 *
	 * @return the status of this catalog
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this catalog.
	 *
	 * @param status the status of this catalog
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this catalog.
	 *
	 * @return the status by user ID of this catalog
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this catalog.
	 *
	 * @param statusByUserId the status by user ID of this catalog
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this catalog.
	 *
	 * @return the status by user uuid of this catalog
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this catalog.
	 *
	 * @param statusByUserUuid the status by user uuid of this catalog
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this catalog.
	 *
	 * @return the status by user name of this catalog
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this catalog.
	 *
	 * @param statusByUserName the status by user name of this catalog
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this catalog.
	 *
	 * @return the status date of this catalog
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this catalog.
	 *
	 * @param statusDate the status date of this catalog
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this catalog is approved.
	 *
	 * @return <code>true</code> if this catalog is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this catalog is denied.
	 *
	 * @return <code>true</code> if this catalog is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this catalog is a draft.
	 *
	 * @return <code>true</code> if this catalog is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this catalog is expired.
	 *
	 * @return <code>true</code> if this catalog is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this catalog is inactive.
	 *
	 * @return <code>true</code> if this catalog is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this catalog is incomplete.
	 *
	 * @return <code>true</code> if this catalog is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this catalog is pending.
	 *
	 * @return <code>true</code> if this catalog is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this catalog is scheduled.
	 *
	 * @return <code>true</code> if this catalog is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}