/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.vnpt.data.cms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DicDataType service. Represents a row in the &quot;VNPT_DicDataType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>vn.vnpt.data.cms.model.impl.DicDataTypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>vn.vnpt.data.cms.model.impl.DicDataTypeImpl</code>.
 * </p>
 *
 * @author vnpt
 * @see DicDataType
 * @generated
 */
@ProviderType
public interface DicDataTypeModel
	extends BaseModel<DicDataType>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dic data type model instance should use the {@link DicDataType} interface instead.
	 */

	/**
	 * Returns the primary key of this dic data type.
	 *
	 * @return the primary key of this dic data type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dic data type.
	 *
	 * @param primaryKey the primary key of this dic data type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dic data type.
	 *
	 * @return the uuid of this dic data type
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dic data type.
	 *
	 * @param uuid the uuid of this dic data type
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the dic data type ID of this dic data type.
	 *
	 * @return the dic data type ID of this dic data type
	 */
	public long getDicDataTypeId();

	/**
	 * Sets the dic data type ID of this dic data type.
	 *
	 * @param dicDataTypeId the dic data type ID of this dic data type
	 */
	public void setDicDataTypeId(long dicDataTypeId);

	/**
	 * Returns the group ID of this dic data type.
	 *
	 * @return the group ID of this dic data type
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dic data type.
	 *
	 * @param groupId the group ID of this dic data type
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dic data type.
	 *
	 * @return the company ID of this dic data type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dic data type.
	 *
	 * @param companyId the company ID of this dic data type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dic data type.
	 *
	 * @return the user ID of this dic data type
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dic data type.
	 *
	 * @param userId the user ID of this dic data type
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dic data type.
	 *
	 * @return the user uuid of this dic data type
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dic data type.
	 *
	 * @param userUuid the user uuid of this dic data type
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dic data type.
	 *
	 * @return the user name of this dic data type
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dic data type.
	 *
	 * @param userName the user name of this dic data type
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dic data type.
	 *
	 * @return the create date of this dic data type
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dic data type.
	 *
	 * @param createDate the create date of this dic data type
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dic data type.
	 *
	 * @return the modified date of this dic data type
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dic data type.
	 *
	 * @param modifiedDate the modified date of this dic data type
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this dic data type.
	 *
	 * @return the status of this dic data type
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this dic data type.
	 *
	 * @param status the status of this dic data type
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this dic data type.
	 *
	 * @return the status by user ID of this dic data type
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this dic data type.
	 *
	 * @param statusByUserId the status by user ID of this dic data type
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this dic data type.
	 *
	 * @return the status by user uuid of this dic data type
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this dic data type.
	 *
	 * @param statusByUserUuid the status by user uuid of this dic data type
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this dic data type.
	 *
	 * @return the status by user name of this dic data type
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this dic data type.
	 *
	 * @param statusByUserName the status by user name of this dic data type
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this dic data type.
	 *
	 * @return the status date of this dic data type
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this dic data type.
	 *
	 * @param statusDate the status date of this dic data type
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this dic data type.
	 *
	 * @return the name of this dic data type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dic data type.
	 *
	 * @param name the name of this dic data type
	 */
	public void setName(String name);

	/**
	 * Returns the code of this dic data type.
	 *
	 * @return the code of this dic data type
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this dic data type.
	 *
	 * @param code the code of this dic data type
	 */
	public void setCode(String code);

	/**
	 * Returns the length of this dic data type.
	 *
	 * @return the length of this dic data type
	 */
	public int getLength();

	/**
	 * Sets the length of this dic data type.
	 *
	 * @param length the length of this dic data type
	 */
	public void setLength(int length);

	/**
	 * Returns <code>true</code> if this dic data type is approved.
	 *
	 * @return <code>true</code> if this dic data type is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this dic data type is denied.
	 *
	 * @return <code>true</code> if this dic data type is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this dic data type is a draft.
	 *
	 * @return <code>true</code> if this dic data type is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this dic data type is expired.
	 *
	 * @return <code>true</code> if this dic data type is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this dic data type is inactive.
	 *
	 * @return <code>true</code> if this dic data type is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this dic data type is incomplete.
	 *
	 * @return <code>true</code> if this dic data type is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this dic data type is pending.
	 *
	 * @return <code>true</code> if this dic data type is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this dic data type is scheduled.
	 *
	 * @return <code>true</code> if this dic data type is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}